//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrexovaVar9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jurnal_lecheniya
    {
        public int id { get; set; }
        public int id_Pacient { get; set; }
        public int id_Diagnoz { get; set; }
        public int id_Lechenie { get; set; }
        public int id_Vrach { get; set; }
        public System.DateTime Date_postupleniya { get; set; }
        public Nullable<System.DateTime> Date_vipiski { get; set; }
        public int id_Sostoyanie { get; set; }
        public Nullable<int> id_Oslojnenie { get; set; }
    
        public virtual Diagnoz Diagnoz { get; set; }
        public virtual Lechenie Lechenie { get; set; }
        public virtual Oslojnenie Oslojnenie { get; set; }
        public virtual Pacient Pacient { get; set; }
        public virtual Sostoyanie Sostoyanie { get; set; }
        public virtual Vrach Vrach { get; set; }
    }
}
