//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrexovaVar9
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicadbEntities : DbContext
    {
        private static ClinicadbEntities _entity;
        public ClinicadbEntities()
            : base("name=ClinicadbEntities")
        {
        }
        public static ClinicadbEntities GetContext()
        {
            if (_entity == null)
                _entity = new ClinicadbEntities();
            return _entity;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Diagnoz> Diagnoz { get; set; }
        public virtual DbSet<Jurnal_lecheniya> Jurnal_lecheniya { get; set; }
        public virtual DbSet<Lechenie> Lechenie { get; set; }
        public virtual DbSet<Oslojnenie> Oslojnenie { get; set; }
        public virtual DbSet<Pacient> Pacient { get; set; }
        public virtual DbSet<Sostoyanie> Sostoyanie { get; set; }
        public virtual DbSet<Streets> Streets { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Vrach> Vrach { get; set; }
    }
}
